### ISSUE TITLE
Wire up settings to actually pick books of scripture

### ISSUE THREAD

**Issue by gshigeto** [jbw91/scripture-golf#9]
When I disable a certain book of scripture, don't show the disabled book of scripture in the guess section of play.

**Comment by johnbwoodruff** [comment]
Thanks man! I meant to leave a little disclaimer on that page that that functionality was not quite implemented yet. But this is awesome because I just realized I didn't have an issue for it! :P

**Comment by johnbwoodruff** [comment]
This is done. Not only does it only present scriptures from the books you select, it also removes the options to pick other books when guessing.
